import { z } from 'zod';
export const emailSchema = z.string().email('Invalid email');
export const latSchema = z.number().min(-90).max(90);
export const lonSchema = z.number().min(-180).max(180);
export const priceSchema = z.number().positive().max(100000000);
export const productSchema = z.object({name:z.string().min(1).max(200),category:z.string().max(100).optional(),price:priceSchema,unit:z.string().max(50).optional()});
export const productsSchema = z.array(productSchema).max(100);
export const vendorCreateSchema = z.object({name:z.string().min(1).max(200),category:z.string().min(1).max(100),description:z.string().max(2000).optional(),lat:latSchema,lon:lonSchema,products:productsSchema.optional()});
export const productCreateSchema = z.object({vendorId:z.string().uuid('Invalid vendor ID'),name:z.string().min(1).max(200),category:z.string().max(100).optional(),price:priceSchema,unit:z.string().max(50).optional()});
export function validateBody(schema){return async(request)=>{try{const body=await request.json();const validated=schema.parse(body);return{success:true,data:validated};}catch(error){if(error instanceof z.ZodError){const messages=error.errors.map(e=>e.path.join('.')+': '+e.message);return{success:false,error:messages.join(', ')};}return{success:false,error:'Invalid JSON';}}};
export async function parseAndValidate(request,schema){try{const body=await request.json();return{success:true,data:schema.parse(body)}}catch(error){if(error instanceof z.ZodError){return{success:false,error:'Validation failed',details:error.errors.map(e=>({field:e.path.join('.'),message:e.message}))};}return{success:false,error:'Invalid request body';}};