// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/auth/signin": {
    params: {};
  };
  "/map": {
    params: {};
  };
  "/vendor": {
    params: {};
  };
  "/vendor/dashboard": {
    params: {};
  };
  "/vendor/messages": {
    params: {};
  };
  "/vendor/onboarding": {
    params: {};
  };
  "/vendor/products": {
    params: {};
  };
  "/vendor/requests": {
    params: {};
  };
  "/__create/social-dev-shim": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account/logout" | "/account/signin" | "/account/signup" | "/auth/signin" | "/map" | "/vendor" | "/vendor/dashboard" | "/vendor/messages" | "/vendor/onboarding" | "/vendor/products" | "/vendor/requests" | "/__create/social-dev-shim" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./auth/signin/page.jsx": {
    id: "auth/signin/page";
    page: "/auth/signin";
  };
  "./map/page.jsx": {
    id: "map/page";
    page: "/map";
  };
  "./vendor/page.jsx": {
    id: "vendor/page";
    page: "/vendor";
  };
  "./vendor/dashboard/page.jsx": {
    id: "vendor/dashboard/page";
    page: "/vendor/dashboard";
  };
  "./vendor/messages/page.jsx": {
    id: "vendor/messages/page";
    page: "/vendor/messages";
  };
  "./vendor/onboarding/page.jsx": {
    id: "vendor/onboarding/page";
    page: "/vendor/onboarding";
  };
  "./vendor/products/page.jsx": {
    id: "vendor/products/page";
    page: "/vendor/products";
  };
  "./vendor/requests/page.jsx": {
    id: "vendor/requests/page";
    page: "/vendor/requests";
  };
  "./__create/social-dev-shim/page.jsx": {
    id: "__create/social-dev-shim/page";
    page: "/__create/social-dev-shim";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "account/signup/page": typeof import("./src/app/./account/signup/page.jsx");
  "auth/signin/page": typeof import("./src/app/./auth/signin/page.jsx");
  "map/page": typeof import("./src/app/./map/page.jsx");
  "vendor/page": typeof import("./src/app/./vendor/page.jsx");
  "vendor/dashboard/page": typeof import("./src/app/./vendor/dashboard/page.jsx");
  "vendor/messages/page": typeof import("./src/app/./vendor/messages/page.jsx");
  "vendor/onboarding/page": typeof import("./src/app/./vendor/onboarding/page.jsx");
  "vendor/products/page": typeof import("./src/app/./vendor/products/page.jsx");
  "vendor/requests/page": typeof import("./src/app/./vendor/requests/page.jsx");
  "__create/social-dev-shim/page": typeof import("./src/app/./__create/social-dev-shim/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};