// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/map": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/user/profile": {
    params: {};
  };
  "/vendor": {
    params: {};
  };
  "/vendor/dashboard": {
    params: {};
  };
  "/vendor/messages": {
    params: {};
  };
  "/vendor/onboarding": {
    params: {};
  };
  "/vendor/products": {
    params: {};
  };
  "/vendor/requests": {
    params: {};
  };
  "/vendor/settings": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account" | "/auth" | "/map" | "/settings" | "/user/profile" | "/vendor" | "/vendor/dashboard" | "/vendor/messages" | "/vendor/onboarding" | "/vendor/products" | "/vendor/requests" | "/vendor/settings" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/page.jsx": {
    id: "account/page";
    page: "/account";
  };
  "./auth/page.jsx": {
    id: "auth/page";
    page: "/auth";
  };
  "./map/page.jsx": {
    id: "map/page";
    page: "/map";
  };
  "./settings/page.jsx": {
    id: "settings/page";
    page: "/settings";
  };
  "./user/profile/page.jsx": {
    id: "user/profile/page";
    page: "/user/profile";
  };
  "./vendor/page.jsx": {
    id: "vendor/page";
    page: "/vendor";
  };
  "./vendor/dashboard/page.jsx": {
    id: "vendor/dashboard/page";
    page: "/vendor/dashboard";
  };
  "./vendor/messages/page.jsx": {
    id: "vendor/messages/page";
    page: "/vendor/messages";
  };
  "./vendor/onboarding/page.jsx": {
    id: "vendor/onboarding/page";
    page: "/vendor/onboarding";
  };
  "./vendor/products/page.jsx": {
    id: "vendor/products/page";
    page: "/vendor/products";
  };
  "./vendor/requests/page.jsx": {
    id: "vendor/requests/page";
    page: "/vendor/requests";
  };
  "./vendor/settings/page.jsx": {
    id: "vendor/settings/page";
    page: "/vendor/settings";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "account/page": typeof import("./src/app/./account/page.jsx");
  "auth/page": typeof import("./src/app/./auth/page.jsx");
  "map/page": typeof import("./src/app/./map/page.jsx");
  "settings/page": typeof import("./src/app/./settings/page.jsx");
  "user/profile/page": typeof import("./src/app/./user/profile/page.jsx");
  "vendor/page": typeof import("./src/app/./vendor/page.jsx");
  "vendor/dashboard/page": typeof import("./src/app/./vendor/dashboard/page.jsx");
  "vendor/messages/page": typeof import("./src/app/./vendor/messages/page.jsx");
  "vendor/onboarding/page": typeof import("./src/app/./vendor/onboarding/page.jsx");
  "vendor/products/page": typeof import("./src/app/./vendor/products/page.jsx");
  "vendor/requests/page": typeof import("./src/app/./vendor/requests/page.jsx");
  "vendor/settings/page": typeof import("./src/app/./vendor/settings/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};