import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const apiDir = join(__dirname, '../src/app/api');

function findRouteFiles(dir) {
	const files = readdirSync(dir);
	let routes = [];
	for (const file of files) {
		const filePath = join(dir, file);
		const stat = statSync(filePath);
		if (stat.isDirectory()) {
			routes = routes.concat(findRouteFiles(filePath));
		} else if (file === 'route.js') {
			routes.push(filePath);
		}
	}
	return routes;
}

const routeFiles = findRouteFiles(apiDir);
const outputPath = join(__dirname, 'generated-routes.ts');

let imports = '';
let entries = [];

for (const [i, filePath] of routeFiles.entries()) {
	const relative = filePath
		.replace(/\\/g, '/')
		.replace(/^.*\/src\/app\/api\//, '')
		.replace(/\/route\.js$/, '');
	const varName = `r${i}`;
	const importPath = `../src/app/api/${relative}/route.js`;
	imports += `import * as ${varName} from '${importPath}';\n`;

	const segments = relative.split('/');
	const honoPath = '/' + segments.map(s => {
		const m = s.match(/^\[(\.{3})?([^\]]+)\]$/);
		return m ? (m[1] === '...' ? `:${m[2]}{.+}` : `:${m[2]}`) : s;
	}).join('/');

	entries.push(`  '${honoPath}': ${varName} as any`);
}

const code = `// Auto-generated by generate-routes.mjs — DO NOT EDIT
import { Hono } from 'hono';
import type { Handler } from 'hono/types';

${imports}
const routeModules: Record<string, Record<string, Function>> = {
${entries.join(',\n')}
};

const api = new Hono();

for (const [path, module] of Object.entries(routeModules)) {
  for (const method of ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'] as const) {
    const handlerFn = module[method];
    if (handlerFn) {
      const handler: Handler = async (c) => {
        return await handlerFn(c.req.raw, { params: c.req.param() });
      };
      (api as any)[method.toLowerCase()](path, handler);
    }
  }
}

export { api };
`;

writeFileSync(outputPath, code);
console.log(`Generated ${outputPath} with ${routeFiles.length} routes`);
